#!/usr/bin/python

import fileinput
import os
import sys

with open('codeHere.txt', 'r') as file:
    filedata = file.read()

filedata = filedata.replace('aaaa', '`')
filedata = filedata.replace('aaab', '~')
filedata = filedata.replace('aaac', '1')
filedata = filedata.replace('aaad', '!')
filedata = filedata.replace('aaba', '2')
filedata = filedata.replace('aabb', '@')
filedata = filedata.replace('aabc', '3')
filedata = filedata.replace('aabd', '#')
filedata = filedata.replace('aaca', '4')
filedata = filedata.replace('aacb', '$')
filedata = filedata.replace('aacc', '5')
filedata = filedata.replace('aacd', '%')
filedata = filedata.replace('aada', '6')
filedata = filedata.replace('aadb', '^')
filedata = filedata.replace('aadc', '7')
filedata = filedata.replace('aadd', '&')
filedata = filedata.replace('abaa', '8')
filedata = filedata.replace('abab', '*')
filedata = filedata.replace('abac', '9')
filedata = filedata.replace('abad', '(')
filedata = filedata.replace('abba', '0')
filedata = filedata.replace('abbb', ')')
filedata = filedata.replace('abbc', '-')
filedata = filedata.replace('abbd', '_')
filedata = filedata.replace('abca', '=')
filedata = filedata.replace('abcb', '+')
filedata = filedata.replace('abcc', '[')
filedata = filedata.replace('abcd', '{')
filedata = filedata.replace('abda', ']')
filedata = filedata.replace('abdb', '}')
filedata = filedata.replace('abdc', '\\')
filedata = filedata.replace('abdd', '|')
filedata = filedata.replace('acaa', ';')
filedata = filedata.replace('acab', ':')
filedata = filedata.replace('acac', '\'')
filedata = filedata.replace('acad', '"')
filedata = filedata.replace('acba', ',')
filedata = filedata.replace('acbb', '<')
filedata = filedata.replace('acbc', '.')
filedata = filedata.replace('acbd', '>')
filedata = filedata.replace('acca', '/')
filedata = filedata.replace('accb', '?')
filedata = filedata.replace('accc', 'q')
filedata = filedata.replace('accd', 'Q')
filedata = filedata.replace('acda', 'w')
filedata = filedata.replace('acdb', 'W')
filedata = filedata.replace('acdc', 'e')
filedata = filedata.replace('acdd', 'E')
filedata = filedata.replace('adaa', 'r')
filedata = filedata.replace('adab', 'R')
filedata = filedata.replace('adac', 't')
filedata = filedata.replace('adad', 'T')
filedata = filedata.replace('adba', 'y')
filedata = filedata.replace('adbb', 'Y')
filedata = filedata.replace('adbc', 'u')
filedata = filedata.replace('adbd', 'U')
filedata = filedata.replace('adca', 'i')
filedata = filedata.replace('adcb', 'I')
filedata = filedata.replace('adcc', 'o')
filedata = filedata.replace('adcd', 'O')
filedata = filedata.replace('adda', 'p')
filedata = filedata.replace('addb', 'P')
filedata = filedata.replace('addc', 'a')
filedata = filedata.replace('addd', 'A')
filedata = filedata.replace('baaa', 's')
filedata = filedata.replace('baab', 'S')
filedata = filedata.replace('baac', 'd')
filedata = filedata.replace('baad', 'D')
filedata = filedata.replace('baba', 'f')
filedata = filedata.replace('babb', 'F')
filedata = filedata.replace('babc', 'g')
filedata = filedata.replace('babd', 'G')
filedata = filedata.replace('baca', 'h')
filedata = filedata.replace('bacb', 'H')
filedata = filedata.replace('bacc', 'j')
filedata = filedata.replace('bacd', 'J')
filedata = filedata.replace('bada', 'k')
filedata = filedata.replace('badb', 'K')
filedata = filedata.replace('badc', 'l')
filedata = filedata.replace('badd', 'L')
filedata = filedata.replace('bbaa', 'z')
filedata = filedata.replace('bbab', 'Z')
filedata = filedata.replace('bbac', 'x')
filedata = filedata.replace('bbad', 'X')
filedata = filedata.replace('bbba', 'c')
filedata = filedata.replace('bbbb', 'C')
filedata = filedata.replace('bbbc', 'v')
filedata = filedata.replace('bbbd', 'V')
filedata = filedata.replace('bbca', 'b')
filedata = filedata.replace('bbcb', 'B')
filedata = filedata.replace('bbcc', 'n')
filedata = filedata.replace('bbcd', 'N')
filedata = filedata.replace('bbda', 'm')
filedata = filedata.replace('bbdb', 'M')
filedata = filedata.replace('bbdc', ' ')
filedata = filedata.replace('.', '')

with open('dontEdit.py', 'w') as file:
    file.write("#!/usr/bin/python\n\n")
    file.write(filedata)
